### ISSUE TITLE
BRIDGE FROM SEPOLIA TESTNET TO BNB CHAIN TESTNET 

### ISSUE THREAD

**Issue by zeusofweb** [beyond-btc/feedback#14]
### Contact details

https://x.com/ZeusofWeb

### What happened?

I was expecting the bridge to go smoothly like when i bridge eth sepolia - bitcoin testnet but i ended up having issues 

I have attached a screenshot to illustrate the issue.

![{2CE5F940-1D99-4D31-9420-234F742D007B}](https://github.com/user-attachments/assets/bf9bd51b-083a-407f-b93f-763c01b60b08)

### On which browser(s) did you encounter the issue?

Chrome

**Comment by sunnybeyond** [comment]
Need more info. Links to transaction, etc.
