### ISSUE TITLE
Beyond app feedback + Suggestions

### ISSUE THREAD

**Issue by YAMISHKA02** [beyond-btc/feedback#15]
The bridging functionality works well—transactions are sent and received without issues, so it fulfills its purpose effectively.

It would be great to add support for the Rabby Wallet, as it's becoming quite popular now.

Also, in the history tab, only incomplete transactions are displayed. When I bridged, the transactions showed up only while they were in progress. Once they were completed, they disappeared from the history, which makes it harder to track past transactions.

I'm also unsure about the total balance tab, especially when using the testnet. How is the balance calculated in this case?

Additionally, when we initiate a bridge, there's no way to check the token balance. For instance, I could try to bridge 1 ETH without actually having any ETH in my wallet, which could lead to confusion.

I hope this feedback is helpful. Thank you very much!

**Comment by sunnybeyond** [comment]
Cannot reproduce the history issue, seems to work fine. Balance is due to it being testnet. token balance is checkable, but not on main page.
