### ISSUE TITLE
Display Bridge History

### ISSUE THREAD

**Issue by naprikole154** [beyond-btc/feedback#167]
### Contact details

naprikole154@gmail.com, https://x.com/MrT47080974

### Is your feature request related to a problem? Please explain.

It would be useful to have a transaction history that shows all previous bridges, so users can track their past transactions easily.

### Describe the solution you'd like

Add a "Transaction History" section that logs all completed bridges.

**Comment by sunnybeyond** [comment]
There is a history function readily existent.
