### ISSUE TITLE
Bridge Button Inactive

### ISSUE THREAD

**Issue by abuzerkripter** [beyond-btc/feedback#169]
### Contact details

abuzerkripter@gmail.com, https://x.com/Venkata55800181

### What happened?

The bridge button sometimes stays inactive even when there are enough funds and the right network is selected, making it impossible to complete the transaction.

Expected Behavior:
The bridge button should be clickable when all requirements are met

### On which browser(s) did you encounter the issue?

Firefox

**Comment by sunnybeyond** [comment]
Can't do much without screenshots.
