### ISSUE TITLE
Feedback about Beyond bridge

### ISSUE THREAD

**Issue by Bogdan0112** [beyond-btc/feedback#17]
![Без имени1](https://github.com/user-attachments/assets/19d74ecf-ac0e-459f-a80a-4d3ab66c89a8)
### Contact details

https://x.com/bogdan_chop

### What happened?

Asset bridge from Sepolia Testnet and BNB Chain Testnet to Bitcoin Testnet does not work. When sending funds from the chain, tokens are approved, but the bridge button is inactive. But sending tokens between Sepolia Testnet and BNB Chain Testnet networks is successful, tokens arrive within 5 minutes from one network to another.

### On which browser(s) did you encounter the issue?

Edge

**Comment by w3theo** [comment]
you probably had mainnet btc address in the output field, not testnet, thats why it was disabled
