### ISSUE TITLE
Error Message Not Clear

### ISSUE THREAD

**Issue by zzzesc80** [beyond-btc/feedback#176]
### Contact details

zzzesc80@gmail.com, https://x.com/johnkenned25191

### What happened?

When a transaction fails, the error message doesn’t explain what went wrong. It just says “Transaction failed,” which isn’t helpful.

Error messages should clearly state the reason for the failure, so users know how to fix the issue.

**Comment by sunnybeyond** [comment]
Low effort. Examples? Suggestions?
