### ISSUE TITLE
Add Network-Specific Gas Fees

### ISSUE THREAD

**Issue by osnanblin** [beyond-btc/feedback#177]
### Contact details

osnanblin@gmail.com, https://x.com/AlessandraKhier

### Is your feature request related to a problem? Please explain.

It would be helpful to see the gas fees for each network before starting a transaction, so users know the cost beforehand.

### Describe the solution you'd like

Show the estimated gas fees for the selected network before the bridge is initiated.

**Comment by sunnybeyond** [comment]
Low effort.
