### ISSUE TITLE
Transaction Not Reflecting in History

### ISSUE THREAD

**Issue by reptiliyd12** [beyond-btc/feedback#180]
### Contact details

reptiliyd12@gmail.com, https://x.com/shamshe21232289

### What happened?

After completing a bridge, the transaction didn’t appear in my transaction history. I had to manually track it using my wallet.

All completed transactions should show up in the transaction history automatically.

**Comment by sunnybeyond** [comment]
Not enough information to work with. Which transaction? URL? Screenshots? etc.
