### ISSUE TITLE
Feedback 

### ISSUE THREAD

**Issue by Codmaaz** [beyond-btc/feedback#2]
I had a great experience using Beyond Tech Bridge to bridge SEPOLIA ETH to BTC. While my first attempt didn't go as planned, I was able to successfully complete the transaction on my second try.
I was impressed with the platform's user-friendly interface and found it easy to navigate, even as a beginner.

**Comment by theo-beyond** [comment]
May I ask you if you encountered any problems on our end at your first go?

**Comment by Codmaaz** [comment]
That's my fault actually In my first try i make gas fees much lower with
the help of advance option
That's my first trx is failed that's all
