### ISSUE TITLE
Beyond testnet bugs

### ISSUE THREAD

**Issue by Loshkass** [beyond-btc/feedback#20]
### Contact details

https://x.com/Oleksii20176458

### What happened?

1. PC 
2. Chrome - dont work. Cant connect Metamask wallet. In Opera wallets are connecting
3. Metamask and Unisat 
5. From ETH to BTC just error. Sent you screenshot, from BTC to ETH inactive sign&pay button in Unisat 
5. In both wallets its testnet network 
<img width="1229" alt="Знімок екрана 2024-10-17 152116" src="https://github.com/user-attachments/assets/77504fc1-9d0c-48c9-a03f-c20678bda3eb">
<img width="311" alt="Знімок екрана 2024-10-17 151817" src="https://github.com/user-attachments/assets/df3bb20f-284f-47b7-aa0e-686dfa5df046">

### On which browser(s) did you encounter the issue?

Chrome, Opera

**Comment by sunnybeyond** [comment]
As the error says, you likely leave insufficient fees for gas.
