### ISSUE TITLE
Support for More Wallets

### ISSUE THREAD

**Issue by ss7252621** [beyond-btc/feedback#202]
### Contact details

ss7252621@gmail.com, https://x.com/khosla_yatin

### Is your feature request related to a problem? Please explain.

Right now, only a limited number of wallets can connect to the platform. It would be great if more wallets, like Trust Wallet and Coinbase Wallet, were supported.

### Describe the solution you'd like

Expand wallet compatibility to include more popular options.

**Comment by sunnybeyond** [comment]
Low effort.
