### ISSUE TITLE
Include a Tutorial Section

### ISSUE THREAD

**Issue by jffmoki** [beyond-btc/feedback#205]
### Contact details

https://x.com/ChillaSuvarna, jffmoki@gmail.com

### Is your feature request related to a problem? Please explain.

A lot of users might be new to bridges, so it would help if there was a tutorial section explaining how to bridge tokens and use the platform.

### Describe the solution you'd like

Add a step-by-step guide or video tutorial for beginners.

**Comment by sunnybeyond** [comment]
Low effort.
