### ISSUE TITLE
Price Chart for Tokens

### ISSUE THREAD

**Issue by mrscam169** [beyond-btc/feedback#208]
### Contact details

https://x.com/LucasGXD01

### Is your feature request related to a problem? Please explain.

It would be useful to have a price chart integrated into the platform to see token price fluctuations before completing a transaction.

### Describe the solution you'd like

Add a small price chart for tokens within the bridge interface.

**Comment by sunnybeyond** [comment]
Nice idea, but no effort in presenting it.
