### ISSUE TITLE
Fee Not Displayed Correctly

### ISSUE THREAD

**Issue by lolzesv** [beyond-btc/feedback#233]
### Contact details

https://x.com/pratikm78018658

### What happened?

The transaction fee displayed before the bridge doesn’t match the actual fee that appears when I confirm in my wallet.
______
The fee shown in the bridge interface should match the final fee during confirmation.

### On which browser(s) did you encounter the issue?

Chrome

**Comment by sunnybeyond** [comment]
Low effort.
