### ISSUE TITLE
Application is not loading

### ISSUE THREAD

**Issue by miromind** [beyond-btc/feedback#27]
### Contact details

dmitriyrucapl@gmail.com, x.com/0xPiracydata

### What happened?

I was expecting to open an application but instead I got the following error: Application error: a client-side exception has occurred (see the browser console for more information).
1. Navigate to ['...'](https://app.beyond.tech/)
2. Observe the error Application error: a client-side exception has occurred (see the browser console for more information).

I have attached a screenshot to illustrate the issue.
![beyond2](https://github.com/user-attachments/assets/875a2ad5-690e-4613-ba01-a4f98d7c1d44)

### On which browser(s) did you encounter the issue?

Chrome

**Comment by sunnybeyond** [comment]
Insufficient info to work with. Need browser console screenshot, as stated in the error.
