### ISSUE TITLE
Incorrect Input Value or High Commission

### ISSUE THREAD

**Issue by Gucciganger322** [beyond-btc/feedback#28]
### Contact details

x.com/JgvCC2hcpLyroEE

### What happened?

What i liked:
UI is really nice imo. 
Switching between Metamask and Unisat working smoothly.

Issue:
While bridging from ETH Sepolia to both the BNB and BTC testnets, I encountered an issue with either the input value being incorrect or an unexpectedly high commission. The fees seem disproportionately high, making the transaction costly.
![very high commission or wrong unput value](https://github.com/user-attachments/assets/820c5425-5e88-4146-baff-6dce25f4bb8e)
![same to bnb](https://github.com/user-attachments/assets/d9725258-a830-4677-bb73-19933bb803df)

Suggestion:
Please optimize the transaction fees, as it’s currently very difficult to acquire enough Sepolia ETH for every testnet.

I hope my feedback is helpful in improving the bridging process. Please feel free to reach out if you need further information or additional screenshots.

### On which browser(s) did you encounter the issue?

Chrome

**Comment by sunnybeyond** [comment]
Transaction fees are, i'd say, based on the load on the network. Not by the app.
