### ISSUE TITLE
Beyond Testnet Bugs

### ISSUE THREAD

**Issue by yarosalav1245** [beyond-btc/feedback#34]
### Contact details

https://x.com/mudryj26843

### What happened?

If when transferring funds between Sepolia Testnet and BNB Chain Testnet the bridge works well: tokens arrive within 5 minutes, then when trying to transfer assets to Bitcoin Testnet there is a serious problem. Despite successful approval of tokens, the bridge itself generates an error, although there are enough tokens. This limits the functionality of the bridge and disrupts inter-chain asset transfers. Please resolve this issue to ensure smooth operation of the bridge across all networks, including Bitcoin Testnet.
![Без имени2](https://github.com/user-attachments/assets/e0f8af7d-2768-4211-bcaf-16609a06f2d0)

### On which browser(s) did you encounter the issue?

Chrome

**Comment by sunnybeyond** [comment]
Insufficient information to determine the issue. Please add browser console logs and transaction links.
