### ISSUE TITLE
Wallets and instructions 

### ISSUE THREAD

**Issue by Mimzzz09999** [beyond-btc/feedback#6]
Actually I felt lost while using it, no instructions for using it correctly, feel like need  help center to use it, also add more wallets to be able to use any of them.

**Comment by theo-beyond** [comment]
What part was hard if I can ask? Would like to hear more!
Also we're working on other wallets as you can see the soon tag next to them, we didnt forget them.

**Comment by Mimzzz09999** [comment]
I got tested eth but couldn't to exchange them and didn't find way how if I
am lost
