### ISSUE TITLE
Add faucet portal on main app

### ISSUE THREAD

**Issue by naraag** [beyond-btc/feedback#7]
### Contact details

@naraag

### Is your feature request related to a problem? Please explain.

Please add faucet portal on main app.

Thank you.

bc1p4ge8wzv3ww5enu54wzr0c8hcklu4d0xde5zgafg0myf4lkg4zeaq3lt7rs

### Describe the solution you'd like

Please add faucet portal on main app.

Thank you.

bc1p4ge8wzv3ww5enu54wzr0c8hcklu4d0xde5zgafg0myf4lkg4zeaq3lt7rs

**Comment by theo-beyond** [comment]
we probably wont have faucet for chains, tokens, but fyi that seems like a mainnet address to me, in case you're trying the app.
